# Chapter 4: NumPy

In [1]:
!pip install numpy

In [3]:
%time
list(range(2000000))[:2]

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 10 µs


[0, 1]

In [3]:
import numpy as np

NumPy operations perform better than that of Python's

Example: Multiplication of Python list and NumPy ndarray by 2

In [2]:
my_array = np.arange(10000)
my_list = list(range(10000))

In [3]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 25.4 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 6.92 ms, sys: 74 µs, total: 6.99 ms
Wall time: 6.78 ms


### NumPy ndarray

In [8]:
data = np.random.randn(2,3)
data

array([[-0.34016149,  1.00938447, -1.00288175],
       [ 0.72718222,  0.49938648,  0.66582167]])

In [9]:
data * 10

array([[ -3.40161487,  10.09384473, -10.02881747],
       [  7.27182223,   4.9938648 ,   6.65821665]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
l1 = [3,5,7,1]
a1 = np.array(l1)
a1

array([3, 5, 7, 1])

In [15]:
np.array([[1, 3, 5], [2, 6, 8]])

array([[1, 3, 5],
       [2, 6, 8]])

In [16]:
np.array([[1, 3, 5], [2, 6, 8]]).shape

(2, 3)

In [18]:
np.array([[1, 3, 5], [2, 6, 8]]).dtype

dtype('int64')

#### Creating ndarrays

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.empty((2, 3))
# May return o or garbage values

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# arange is like range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

####  Ndarray Datatypes

In [32]:
arr = np.random.randn(2,2)
print(arr)
arr.astype(np.int32)

[[ 0.45367595  0.23369002]
 [-0.24411963 -1.16778698]]


array([[ 0,  0],
       [ 0, -1]], dtype=int32)

#### Arithemetic Operations with ndarrays
Operations b/w equal-sized arrays are applied element wise

In [33]:
arr = np.array([[1, 3, 5], [2, 6, 8]])
arr

array([[1, 3, 5],
       [2, 6, 8]])

In [34]:
arr * arr

array([[ 1,  9, 25],
       [ 4, 36, 64]])

In [36]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
1 / arr

array([[1.        , 0.33333333, 0.2       ],
       [0.5       , 0.16666667, 0.125     ]])

In [38]:
arr ** 2

array([[ 1,  9, 25],
       [ 4, 36, 64]])

In [40]:
arr > 2

array([[False,  True,  True],
       [False,  True,  True]])

#### Basic Indexing & Slicing

In [45]:
arr = np.arange(15)
print(arr)
print('arr[4]:', arr[4])
print('arr[3:8]:', arr[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
arr[4]: 4
arr[3:8]: [3 4 5 6 7]


In [46]:
arr[3:8] = 50
arr

array([ 0,  1,  2, 50, 50, 50, 50, 50,  8,  9, 10, 11, 12, 13, 14])

In [48]:
arr_slice = arr[3:8]
arr_slice

array([50, 50, 50, 50, 50])

In [49]:
arr_slice[1] = 3
arr

array([ 0,  1,  2, 50,  3, 50, 50, 50,  8,  9, 10, 11, 12, 13, 14])

In [54]:
arr2d = np.array([[1,2,3], [7,8,9], [11,13,14]])
print(arr2d[1])
print(arr2d[1][0])
print(arr2d[1, 1])

[7 8 9]
7
8


In [75]:
print(arr2d)
arr2d[:2, :2]

[[ 1  2  3]
 [ 7  8  9]
 [11 13 14]]


array([[1, 2],
       [7, 8]])

#### Boolean Indexing

In [13]:
names = np.array(['Ali', 'Umer', 'Hamza', 'Ali'])
names == 'Ali'

array([ True, False, False,  True])

In [6]:
data = np.random.randn(4, 3)
data

array([[ 0.30737866,  0.88902134, -0.52355502],
       [-1.14745845, -0.30997277, -1.26754492],
       [-0.50457379, -0.10428279,  1.49999831],
       [ 2.43239237, -1.23519674,  0.55264912]])

In [14]:
data[names == 'Ali']

array([[ 0.30737866,  0.88902134, -0.52355502],
       [ 2.43239237, -1.23519674,  0.55264912]])

In [17]:
data[names == 'Ali', :2]

array([[ 0.30737866,  0.88902134],
       [ 2.43239237, -1.23519674]])

In [19]:
# Set all negative values to 0
data[data < 0 ] = 0
data

array([[0.30737866, 0.88902134, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.49999831],
       [2.43239237, 0.        , 0.55264912]])

#### Fancy Indexing
Indexing using int arrays

In [22]:
data[[3,1,0]]

array([[2.43239237, 0.        , 0.55264912],
       [0.        , 0.        , 0.        ],
       [0.30737866, 0.88902134, 0.        ]])

In [23]:
data[[3,1,0], [1,2,0]]

array([0.        , 0.        , 0.30737866])

#### Transpose

In [25]:
data.T

array([[0.30737866, 0.        , 0.        , 2.43239237],
       [0.88902134, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.49999831, 0.55264912]])

In [28]:
np.dot(data.T, data)

array([[6.01101427, 0.27326619, 1.3442595 ],
       [0.27326619, 0.79035895, 0.        ],
       [1.3442595 , 0.        , 2.555416  ]])